language: generic
git:
  depth: false
env:
  global:
    - VERSION=${TRAVIS_COMMIT:0:8}
    - BRANCH=$TRAVIS_BRANCH
    - PROJECT_NAME=opensiddur-client
    - INSTANCE_BASE=${PROJECT_NAME}-app-${BRANCH//\//-}
    - INSTANCE_NAME=${INSTANCE_BASE}-${VERSION}
    - ZONE=us-west2-a
    - MACHINE_TYPE=g1-small
    - IMAGE=ubuntu-1804-bionic-v20190204
    - IMAGE_PROJECT=ubuntu-os-cloud
    - BOOT_DISK_SIZE_GB=10
    - SERVICE_ACCOUNT=opensiddur-deploy-1@opensiddur-client.iam.gserviceaccount.com
    # DYN_EMAIL
    - secure: "X639CL91V6ORbeh+yCHfUGSpPkb6RfPGXiNo66TNEXhQpIoGgO87YQEbgRsbYnd2w5yCGVdk6g35HWHUGoJJ/HU0fbmYJH9Qhf6u/YClkwGcSruJRaiITEU8+CaxgCcElmMWwpIPxxE1ZTCL7anYVZgH+cbzmh3dYtOu4ZCivh2rHeD//YsS6Enxn8NpAg+bcyyzVEbg2NVqMcXxzjlXSFUtDEeIa9fyDyapFUXC6Cwp+IPLfbl9ljtoaPZRWhavirKHN6+E+6Ix/NgyTw9yMsSZTVQIz5XVzLFFn4pk5CRXYkqDwZ+U5DgDy/ZbIoU2B3ZcTkDr6X72phx+95Odkhbaa8aXEHEIC5Fzg+RtHERJwgdWh4ydxeEx2YNbG15lz1z6ccatkGwa3837kyf6wl2d6GYYGPMYgDXR2b1jsR1EcSO8xNnio9KAHbatNZFS9Jg22luoo8oO1U3iFh0+S0+PFJKLxz5+442vFSbLUUY6McUDT6ALED7eDpL1ciLDJAtqiT8Jyxheo+4T8h32KFaIUqnFeNEKbu3Hi4nzCXzbUFCebokk9HiVnXQU/UkU3l8klWdAHg/a5EoLGl9lihOgbv0hT4PQdhV8gD4cfozPGZomDZ0s8CqIjSrmHlZr3nH5738OH+KdaO3vzASqrvafPNtJl/GgH/9APoG25B4="
    # DYN_USERNAME
    - secure: "o2b02l9Ndo4otnTw3I0d27FqREj1oMUIXqbUbiyODVMcOdSBW3HYexMsomwbPX9OiWngWEiJCY9GvdT1OCTF5IyTlwce8hXQyRg9Y1ZwkQ31s/bI5DvHY4e6Io+UavfON26DgU3+WvCLaK+Mp88gLQQkiVmvugbGaJn4mrxPcxcjylahSmLSbBj7X3rOFI+kwBzqioTQZeDPuAS2omLOTzlzd4+Nf1jifjJd6MCbTCm9srKmxZItPxUM4BrQ2AL0PEqdYrPklLdnsZCb1jz2zgBxz1/H1iPIlOnLcJ4cNs8XZn/p0tQJ1dpR/QMD5CE/ezKphcJVXKhJ8YAW/7yYFofnm+re6VZ3fC8KJCjlRGA3SrtVFXsOsNbhUWvB+RW5IkN3Hr9XOVlVa9d9Nyh/AGtLI5+3ydPkDH0MQeYi1fA/5JPwKtQnJfpQ1ifX2nuQp61Qs9TA28n2NGxXr0YZveFOUVYCn3+uboEs0yC4M6rvWrcdvT7g1IofafIQ0bRaci18d+m/96TiqSPxXh5c45SiW+HqYOO0OYTHEVHcwnsdWAIOgpyUVbpXBoQBVqYJn9EIohJXQ1ZT4BivDlfxJmpezBg9dV/7uk1QvBiBQIyBhT7m3ZCbhUDQiMw6ylifpeWeq4tAly4lwgtTk/rTXPP1KVCiLogduxCaQuoASLc="
    # DYN_PASSWORD
    - secure: "geeugGzQLyyXbrzewQfpSKVQcLkLXKPwR6VbdIpy5T32OSCQkAeQkyXNjgZ24FQ/8y3CJvvFUL8NjTP5usAT+hh3b8/xTrMQ5Wdy6Yoskl3xuQ+ElWHdeoOh9n1NNowLGTyVFKK4JQlLOAskXszhukhSmGGplXBoAAtB6tUzDx+0BZyYlgONTsgTKamHXbHPyKYDYT4beWeEg7NLtay8h0GFJXjjnDLc3g6tDRRJi0tQe1Doscl2Bk8xVGBsSZbQDqRWvajXoAQtw32+BuM5YUKKyoYZ+pXFq3xTDRNn+uqlSoeSxddX26sLG50uBIRF3PIUQGsLn8C/htKmcQ70CCfLyOTJfXsjg9rOZICtvhS2CDRHf/rw1jXh9NxDIIUJkyBpDozUmIYGJMREP5S3HEY9g2lA2y80uM0s6EAvySuSE/Ca/xUZGbr3m6eKtVdAvhk4kKniJ3OAb+pl3+v7unRBuecBWy51jTX5vq0Px725CWZxWXRQtilMXQ7xLu2BxQJj/0x3uetJIAe5VXZwCAu/Amx3W7qDPRtjwWYLz3eBB89rM6BCZS2oBLnzii/1hTdBCpMEIYME2ZmMzoEj9C9OXCAggbVPCTk+jClHYM1wwl4UDgBaVe1Q0Crby6b4zXRgUk4FNQbJJuKStu2KasJl8PsuG5fjMyNFQ7DKDsU="

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
    -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
  - sudo apt-get update -y
  - sudo apt-get install -y google-cloud-sdk
  - openssl aes-256-cbc -K $encrypted_f7e573a7dafa_key -iv $encrypted_f7e573a7dafa_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar zxvf credentials.tar.gz
  - gcloud auth activate-service-account --key-file=client-secret.json
  - gcloud config set project ${PROJECT_NAME}
  - ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine

script:
  - |
    gcloud compute \
      --project=${PROJECT_NAME} instances create ${INSTANCE_NAME} \
      --zone=${ZONE} \
      --machine-type=${MACHINE_TYPE} \
      --network=default \
      --network-tier=PREMIUM \
      --maintenance-policy=MIGRATE \
      --scopes=https://www.googleapis.com/auth/cloud-platform \
      --tags=http-server,https-server \
      --image=${IMAGE} \
      --image-project=${IMAGE_PROJECT} \
      --boot-disk-size=${BOOT_DISK_SIZE_GB}GB \
      --boot-disk-type=pd-standard \
      --boot-disk-device-name=${INSTANCE_NAME} \
      --service-account=${SERVICE_ACCOUNT} \
      --metadata-from-file startup-script=setup/gcloud-startup-script.sh \
      --metadata BRANCH=${BRANCH},DYN_USERNAME=${DYN_USERNAME},DYN_PASSWORD=${DYN_PASSWORD},DYN_EMAIL=${DYN_EMAIL},enable-oslogin=true

